language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

script:
  - ./runTests.sh

before_script:
  - travis_retry composer config -g github-oauth.github.com $GITHUB_ACCESS_TOKEN
  - travis_retry composer install --prefer-dist --no-interaction --optimize-autoloader

sudo: false
